In [24]:
import bs4
import requests
import json
import time
import pandas as pd

In [22]:
movies = pd.DataFrame(columns=['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count'])
i = 52136
for n in range(72534,1000000):
    print(n)
    a = requests.get("https://api.themoviedb.org/3/movie/{}?api_key=0caa07ffd556001d4b0e1b11a485768f".format(n))
    if '"success":false' in a.text:
        pass
    else:
        start = time.time()
        res = json.loads(a.text)
        movies.at[i,'adult'] = res['adult']
        movies.at[i,'backdrop_path'] = res['backdrop_path']
        movies.at[i,'belongs_to_collection'] = res['belongs_to_collection']
        movies.at[i,'budget'] = res['budget']
        movies.at[i,'genres'] = res['genres']
        movies.at[i,'homepage'] = res['homepage']
        movies.at[i,'id'] = res['id']
        movies.at[i,'imdb_id'] = res['imdb_id']
        movies.at[i,'original_language'] = res['original_language']
        movies.at[i,'original_title'] = res['original_title']
        movies.at[i,'overview'] = res['overview']
        movies.at[i,'popularity'] = res['popularity']
        movies.at[i,'poster_path'] = res['poster_path']
        movies.at[i,'production_companies'] = res['production_companies']
        movies.at[i,'production_countries'] = res['production_countries']
        movies.at[i,'release_date'] = res['release_date']
        movies.at[i,'revenue'] = res['revenue']
        movies.at[i,'runtime'] = res['runtime']
        movies.at[i,'spoken_languages'] = res['spoken_languages']
        movies.at[i,'status'] = res['status']
        movies.at[i,'tagline'] = res['tagline']
        movies.at[i,'title'] = res['title']
        movies.at[i,'video'] = res['video']
        movies.at[i,'vote_average'] = res['vote_average']
        movies.at[i,'vote_count'] = res['vote_count']
        i += 1
        end = time.time()
        print((end - start) * 100)

72534
72535
72536

KeyError: 'keywords'

In [25]:
m1 = pd.read_csv('Movies_Custom52135_72533.csv')
m2 = pd.read_csv('Movies_Custom101531_161315.csv')

In [26]:
movies = pd.concat([m1,m2])

In [72]:
movies

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,tags
0,False,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,NaN,0,"[Drama, Comedy, Crime]",NaN,2,tt0094675,fi,Ariel,...,0,73.0,"[{'english_name': 'Finnish', 'iso_639_1': 'fi'...",Released,NaN,Ariel,False,6.8,159,"[Taisto, Kasurinen, is, a, Finnish, coal, mine..."
1,False,/l94l89eMmFKh7na2a1u5q67VgNx.jpg,NaN,0,"[Drama, Comedy]",NaN,3,tt0092149,fi,Varjoja paratiisissa,...,0,74.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Shadows in Paradise,False,7.1,161,"[An, episode, in, the, life, of, Nikander,, a,..."
2,False,/bCXLsO2MJWzYYBJoavGOZN5iqGn.jpg,NaN,4000000,"[Crime, Comedy]",https://www.miramax.com/movie/four-rooms/,5,tt0113101,en,Four Rooms,...,4257354,98.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,False,5.7,2140,"[It's, Ted, the, Bellhop's, first, night, on, ..."
3,False,/5aXp2s4l6g5PcMMesIj63mx8hmJ.jpg,NaN,21000000,"[Action, Thriller, Crime]",NaN,6,tt0107286,en,Judgment Night,...,12136938,110.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Don't move. Don't whisper. Don't even breathe.,Judgment Night,False,6.6,237,"[While, racing, to, a, boxing, match,, Frank,,..."
4,False,NaN,NaN,42000,[Documentary],http://lifeinloops.com,8,tt0825671,en,Life in Loops (A Megacities RMX),...,0,80.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A Megacities remix.,Life in Loops (A Megacities RMX),False,7.5,18,"[Timo, Novotny, labels, his, new, project, an,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101527,False,NaN,NaN,0,[],NaN,161301,tt0132240,tr,Indefensible: The Truth About Edward Brannigan,...,0,91.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Indefensible: The Truth About Edward Brannigan,False,4.7,3,"[Edward, Brannigan, (Brian, Dennehy),, a, vete..."
101528,False,NaN,NaN,0,[Drama],NaN,161303,tt1815998,en,The Playroom,...,0,83.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It's 1975. Do you know where your parents are?,The Playroom,False,5.8,13,"[Four, children, in, their, attic, hideaway, m..."
101529,False,NaN,NaN,0,[Drama],NaN,161308,tt0215532,de,Auslandstournee,...,0,91.0,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,NaN,Tour Abroad,False,0.0,0,"[, Drama, Old]"
101530,False,NaN,NaN,0,[],NaN,161311,tt0393906,en,Tánger,...,0,100.0,"[{'english_name': 'Spanish', 'iso_639_1': 'es'...",Released,NaN,Tánger,False,2.3,2,"[Abdul, Kader, Torres, (Jorge, Perugorria),, s..."
101531,False,/tB7A73JQIhstMVwdCXSsiReuMe9.jpg,NaN,0,[Crime],NaN,161313,tt0056894,en,Cairo,...,0,91.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Where Sinners Meet!,Cairo,False,5.3,4,"[MGM, remake, of, Asphalt, Jungle, set, in, Eg..."

In [27]:
movies.reset_index(inplace=True, drop=True)

In [28]:
movies.isnull().sum()

adult                        0
backdrop_path            47910
belongs_to_collection    93329
budget                       0
genres                       0
homepage                 89079
id                           0
imdb_id                  10626
original_language            0
original_title               0
overview                  5902
popularity                   0
poster_path              16807
production_companies         0
production_countries         0
release_date              2201
revenue                      0
runtime                   1036
spoken_languages             0
status                       0
tagline                  68126
title                        0
video                        0
vote_average                 0
vote_count                   0
dtype: int64

In [29]:
movies

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,2,tt0094675,fi,Ariel,...,1988-10-21,0,73.0,"[{'english_name': 'Finnish', 'iso_639_1': 'fi'...",Released,NaN,Ariel,False,6.8,159
1,False,/l94l89eMmFKh7na2a1u5q67VgNx.jpg,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,3,tt0092149,fi,Varjoja paratiisissa,...,1986-10-17,0,74.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Shadows in Paradise,False,7.1,161
2,False,/bCXLsO2MJWzYYBJoavGOZN5iqGn.jpg,NaN,4000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",https://www.miramax.com/movie/four-rooms/,5,tt0113101,en,Four Rooms,...,1995-12-09,4257354,98.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,False,5.7,2140
3,False,/5aXp2s4l6g5PcMMesIj63mx8hmJ.jpg,NaN,21000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,6,tt0107286,en,Judgment Night,...,1993-10-15,12136938,110.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Don't move. Don't whisper. Don't even breathe.,Judgment Night,False,6.6,237
4,False,NaN,NaN,42000,"[{'id': 99, 'name': 'Documentary'}]",http://lifeinloops.com,8,tt0825671,en,Life in Loops (A Megacities RMX),...,2006-01-01,0,80.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A Megacities remix.,Life in Loops (A Megacities RMX),False,7.5,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101527,False,NaN,NaN,0,[],NaN,161301,tt0132240,tr,Indefensible: The Truth About Edward Brannigan,...,1997-11-25,0,91.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Indefensible: The Truth About Edward Brannigan,False,4.7,3
101528,False,NaN,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,161303,tt1815998,en,The Playroom,...,2013-02-06,0,83.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It's 1975. Do you know where your parents are?,The Playroom,False,5.8,13
101529,False,NaN,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,161308,tt0215532,de,Auslandstournee,...,2000-07-01,0,91.0,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,NaN,Tour Abroad,False,0.0,0
101530,False,NaN,NaN,0,[],NaN,161311,tt0393906,en,Tánger,...,2004-05-21,0,100.0,"[{'english_name': 'Spanish', 'iso_639_1': 'es'...",Released,NaN,Tánger,False,2.3,2
101531,False,/tB7A73JQIhstMVwdCXSsiReuMe9.jpg,NaN,0,"[{'id': 80, 'name': 'Crime'}]",NaN,161313,tt0056894,en,Cairo,...,1963-07-17,0,91.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Where Sinners Meet!,Cairo,False,5.3,4

In [30]:
import ast
ast.literal_eval(movies.genres[0])

[{'id': 18, 'name': 'Drama'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'}]

In [31]:
def convert(x):
    l = []
    x = ast.literal_eval(x)
    for i in x:
        l.append(i['name'])
    return l

In [32]:
movies.genres = movies.genres.apply(convert)
# movies.keywords = movies.keywords.apply(convert)
movies.production_companies = movies.production_companies.apply(convert)

In [35]:
movies.production_companies

0                               [Villealfa Filmproductions]
1                               [Villealfa Filmproductions]
2                                   [Miramax, A Band Apart]
3            [Universal Pictures, Largo Entertainment, JVC]
4                                                 [inLoops]
                                ...
101527                                                   []
101528                                                   []
101529                                                   []
101530                                                   []
101531    [Lawrence P. Bachmann Productions, Metro-Goldw...
Name: production_companies, Length: 101532, dtype: object

In [36]:
def convert3(x):
    l = []
    c = 0
    x = ast.literal_eval(x)
    for i in x:
        if c != 3:
            l.append(i['name'])
            c = c + 1
        else :
            break
    return l

In [37]:
movies.cast = movies.cast.apply(convert3)

AttributeError: 'DataFrame' object has no attribute 'cast'

In [38]:
movies.release_date = pd.to_datetime(movies.release_date)

In [39]:
def year_binning(x):
    l = []
    if x.year > 2005:
        l.append('New')
    else:
        l.append('Old')
    return l

In [40]:
movies.release_date = movies.release_date.apply(year_binning)

In [49]:
movies.overview = movies.overview.apply(lambda x : x.split(' '))

AttributeError: 'float' object has no attribute 'split'

In [59]:
movies.overview.fillna("", inplace=True)

In [60]:
movies.overview = movies.overview.apply(lambda x : x.split(' '))

In [62]:
movies.overview

0         [Taisto, Kasurinen, is, a, Finnish, coal, mine...
1         [An, episode, in, the, life, of, Nikander,, a,...
2         [It's, Ted, the, Bellhop's, first, night, on, ...
3         [While, racing, to, a, boxing, match,, Frank,,...
4         [Timo, Novotny, labels, his, new, project, an,...
                                ...
101527    [Edward, Brannigan, (Brian, Dennehy),, a, vete...
101528    [Four, children, in, their, attic, hideaway, m...
101529                                                   []
101530    [Abdul, Kader, Torres, (Jorge, Perugorria),, s...
101531    [MGM, remake, of, Asphalt, Jungle, set, in, Eg...
Name: overview, Length: 101532, dtype: object

In [65]:
movies.genres = movies.genres.apply(lambda x :[i.replace(" ","") for i in x])

In [66]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['production_companies'] + movies['release_date']

In [73]:
new_df = movies[['id','title','tags']]

In [75]:
new_df

,id,title,tags
0,2,Ariel,"[Taisto, Kasurinen, is, a, Finnish, coal, mine..."
1,3,Shadows in Paradise,"[An, episode, in, the, life, of, Nikander,, a,..."
2,5,Four Rooms,"[It's, Ted, the, Bellhop's, first, night, on, ..."
3,6,Judgment Night,"[While, racing, to, a, boxing, match,, Frank,,..."
4,8,Life in Loops (A Megacities RMX),"[Timo, Novotny, labels, his, new, project, an,..."
...,...,...,...
101527,161301,Indefensible: The Truth About Edward Brannigan,"[Edward, Brannigan, (Brian, Dennehy),, a, vete..."
101528,161303,The Playroom,"[Four, children, in, their, attic, hideaway, m..."
101529,161308,Tour Abroad,"[, Drama, Old]"
101530,161311,Tánger,"[Abdul, Kader, Torres, (Jorge, Perugorria),, s..."
101531,161313,Cairo,"[MGM, remake, of, Asphalt, Jungle, set, in, Eg..."

In [76]:
new_df.tags = new_df.tags.apply(lambda x: " ".join(x))

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [78]:
new_df.tags = new_df.tags.apply(lambda x : x.lower())

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [80]:
import nltk

In [81]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [82]:
def stem(x):
    l = []
    for i in x.split(' '):
        l.append(ps.stem(i))
    return " ".join(l)

In [83]:
new_df.tags = new_df.tags.apply(stem)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [86]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [87]:
cv.get_feature_names()

['00',
 '000',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1920',
 '1930',
 '1939',
 '1940',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '1st',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '25th',
 '26',
 '27',
 '28',
 '29',
 '30',
 '300',
 '31',
 '35',
 '3d',
 '40',
 '45',
 '50',
 '500',
 '60',
 '70',
 '80',
 '90',
 'aaron',
 'ab',
 'abandon',
 'abc',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abroad',
 'abs',
 'absolut',
 'absurd',
 'abus',
 'abuse',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'accord',
 'account',
 'accus',
 'ace',
 'achiev',
 'acoust',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'address',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adult',
 'adulthood',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'af',
 'affair',
 'affect',
 'affection',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'afternoon',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggress',
 'ago',
 'agre',
 'ah',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airplan',
 'airport',
 'aka',
 'al',
 'alain',
 'alan',
 'alarm',
 'alaska',
 'albert',
 'alberto',
 'album',
 'albums',
 'alcohol',
 'alex',
 'alexand',
 'alexi',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alike',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alley',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alp',
 'alpin',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amor',
 'amp',
 'amsterdam',
 'amus',
 'ana',
 'anal',
 'ancient',
 'anderson',
 'andi',
 'andr',
 'andrea',
 'andrew',
 'andré',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angl',
 'angri',
 'ani',
 'anim',
 'animals',
 'animation',
 'anita',
 'ann',
 'anna',
 'anne',
 'anni',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'antholog',
 'anthoni',
 'anti',
 'antic',
 'anticip',
 'antiqu',
 'antoin',
 'anton',
 'antonio',
 'anymore',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apocalypt',
 'apollo',
 'appar',
 'appeal',
 'appear',
 'appears',
 'appl',
 'appli',
 'appoint',
 'appreci',
 'approach',
 'approv',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'archiv',
 'arctic',
 'ard',
 'area',
 'aren',
 'arena',
 'argentina',
 'argu',
 'argument',
 'ari',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armi',
 'armor',
 'army',
 'arnold',
 'arrang',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrives',
 'arrog',
 'art',
 'arthur',
 'artist',
 'artists',
 'arts',
 'asa',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspir',
 'ass',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'astonish',
 'astronaut',
 'asylum',
 'athlet',
 'atlant',
 'atlanti',
 'atmospher',
 'atom',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attention',
 'attitud',
 'attorney',
 'attract',
 'au',
 'audienc',
 'audience',
 'audio',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'austrian',
 'authent',
 'author',
 'authorities',
 'auto',
 'autumn',
 'avail',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backstag',
 'backyard',
 'bad',
 'badli',
 'bag',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'ban',
 'band',
 'bandai',
 'bandit',
 'bang',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'banner',
 'bar',
 'barbara',
 'barber',
 'barcelona',
 'bare',
 'bargain',
 'barney',
 'baron',
 'barrandov',
 'barri',
 'bars',
 'bas',
 'base',
 'basebal',
 'basement',
 'basic',
 'basketbal',
 'bass',
 'bat',
 'bath',
 'battl',
 'battle',
 'bavaria',
 'bay',
 'bbc',
 'beach',
 'bear',
 'beast',
 'beat',
 'beaten',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'begun',
 'behavior',
 'behaviour',
 'beij',
 'belief',
 'believ',
 'bell',
 'bellat',
 'belong',
 'belov',
 'belt',
 'ben',
 'bend',
 'beneath',
 'benefit',
 'benjamin',
 'benni',
 'bent',
 'berlin',
 'bernard',
 'besid',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'bi',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'billi',
 'billion',
 'biograph',
 'biographi',
 'biolog',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blake',
 'blame',
 'blast',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'blossom',
 'blow',
 'blu',
 'blue',
 'blues',
 'blur',
 'bo',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bomb',
 'bombay',
 'bomber',
 'bond',
 'bone',
 'bonu',
 'book',
 'books',
 'boom',
 'boot',
 'border',
 'bore',
 'born',
 'borrow',
 'boss',
 'boston',
 'bottl',
 'bought',
 'bound',
 'boundari',
 'bounti',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'br',
 'brad',
 'brain',
 'branch',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breathtak',
 'breed',
 'brian',
 'bride',
 'bridg',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'bros',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'bu',
 'bubbl',
 'buck',
 'bud',
 'budapest',
 'buddi',
 'budget',
 'bueno',
 'buffalo',
 'bug',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bumbl',
 'bump',
 'bunch',
 'bunni',
 'burden',
 'buri',
 'burn',
 'burst',
 'bus',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'buster',
 'butch',
 'butcher',
 'butler',
 'butt',
 'buy',
 'ca',
 'cab',
 'cabaret',
 'cabin',
 'cabl',
 'caesar',
 'cafe',
 'café',
 'cage',
 'cal',
 'california',
 'calm',
 'came',
 'camera',
 'cameron',
 'camp',
 'campaign',
 'campu',
 'canada',
 'canadian',
 'canal',
 'cancer',
 'candi',
 'candid',
 'cannib',
 'cannon',
 'canyon',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'caravan',
 'card',
 'care',
 'career',
 'carefre',
 'cargo',
 'caribbean',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carniv',
 'carol',
 'carolina',
 'carri',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'catastroph',
 'catch',
 'catherin',
 'cathol',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cave',
 'cb',
 'cbn',
 'cd',
 'cecchi',
 'celebr',
 'cell',
 'center',
 'centr',
 'central',
 'centuri',
 'century',
 'ceremoni',
 'certain',
 'certainli',
 'chad',
 'chain',
 'chair',
 'challeng',
 'challenge',
 'chamber',
 'champion',
 'championship',
 'championships',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charge',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chat',
 'cheap',
 'cheat',
 'check',
 'cheer',
 'chef',
 'chemic',
 'chen',
 'cheng',
 'chess',
 'cheung',
 'chi',
 'chicago',
 'chick',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chile',
 'chill',
 'china',
 'chines',
 'ching',
 'chip',
 'choic',
 'choice',
 'choir',
 'choos',
 'chosen',
 'chow',
 'chri',
 'christ',
 'christian',
 'christin',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'chung',
 'church',
 'cia',
 'cine',
 'cinema',
 'cinemat',
 'cinematografica',
 'cinematográfica',
 'ciné',
 'cinécinéma',
 'cinéma',
 'cinématographiqu',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'circus',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'cj',
 'clad',
 'claim',
 'clair',
 'clan',
 'clara',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'clau',
 'claud',
 'claudia',
 'clay',
 'clean',
 'clear',
 'clearli',
 'clerk',
 'clever',
 'client',
 'cliff',
 'climax',
 'climb',
 'clinic',
 'clip',
 'clock',
 'close',
 'closer',
 'closest',
 'closet',
 'cloth',
 'cloud',
 'clown',
 'club',
 'clue',
 'clutch',
 'cnc',
 'coach',
 'coal',
 'coast',
 'coastal',
 'cock',
 'code',
 'coffe',
 'coin',
 'coincid',
 'cold',
 'cole',
 'colin',
 'collabor',
 'collaps',
 'collar',
 'colleagu',
 'colleagues',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collin',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'colour',
 'columbia',
 'com',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'command',
 'commando',
 'comment',
 'commentari',
 'commerci',
 'commiss',
 'commission',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compagni',
 'compagnia',
 'compani',
 'companion',
 'company',
 'compar',
 'compel',
 'compet',
 'competit',
 'competition',
 'compil',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'comprehens',
 'compris',
 'compromis',
 'comput',
 'computer',
 'comrad',
 'concentr',
 'concept',
 'concern',
 'concert',
 'condemn',
 'condit',
 'condition',
 'conduct',
 'conductor',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'connect',
 'conquer',
 'consequ',
 ...]

In [88]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

MemoryError: Unable to allocate 76.8 GiB for an array with shape (101532, 101532) and data type float64

In [ ]:
new_df.reset_index(inplace=True,drop=True)

In [ ]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Krrish')